# Labour Force Survey Microdata

[Files from StatsCan](https://www150.statcan.gc.ca/n1/en/catalogue/71M0001X).

## Import and clean raw data

In [ ]:
import pandas as pd
import glob

In [ ]:
# Get all our files and create a blank list to hold them.
all_files = glob.glob("/content/drive/MyDrive/Data/Raw/LFS/*.csv")
li = []

# Loop through all the files, add a new column so we can keep track of what PHU they're from, and add them to our list.
for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)

# Concatenate all the dataframes into one big one, which will be our raw data.
raw = pd.concat(li, axis=0, ignore_index=True)
raw = raw.set_index('REC_NUM')

display(raw)

         SURVYEAR  SURVMNTH  LFSSTAT  PROV  ...  SCHOOLN  EFAMTYPE  AGYOWNK  FINALWT
REC_NUM                                     ...
1            2021        10        1    46  ...      1.0         4      4.0      125
2            2021        10        1    12  ...      1.0         2      NaN      186
3            2021        10        1    47  ...      1.0        10      NaN      181
4            2021        10        1    13  ...      1.0         1      NaN      144
5            2021        10        4    24  ...      NaN        11      NaN      175
...           ...       ...      ...   ...  ...      ...       ...      ...      ...
86858        2021         8        1    48  ...      1.0         3      2.0       98
86859        2021         8        4    59  ...      1.0        11      NaN      231
86860        2021         8        4    59  ...      NaN         1      NaN       76
86861        2021         8        4    35  ...      NaN         1      NaN      148
86862        2021         8        1    24  ...      1.0         2      NaN      398

[259466 rows x 59 columns]

In [ ]:
raw["PROV"] = raw["PROV"].replace({
    10: "Newfoundland and Labrador",
    11: "Prince Edward Island",
    12: "Nova Scotia",
    13: "New Brunswick",
    24: "Quebec",
    35: "Ontario",
    46: "Manitoba",
    47: "Saskatchewan",
    48: "Alberta",
    59: "British Columbia"
})

raw["CMA"] = raw["CMA"].replace({
    0: "Other CMA or non-CMA",
    1: "Quebec City",
    2: "Montreal",
    3: "Ottawa/Gatineau",
    4: "Toronto",
    5: "Hamilton",
    6: "Wininpeg",
    7: "Calgary",
    8: "Edmonton",
    9: "Vancouver"
})

raw["AGE_12"] = raw["AGE_12"].replace({
    1: "15-19",
    2: "20-24",
    3: "25-29",
    4: "30-34",
    5: "35-40",
    6: "41-44",
    7: "45-49",
    8: "50-54",
    9: "55-59",
    10: "60-64",
    11: "65-69",
    12: "70+"
})

raw["AGE_6"] = raw["AGE_6"].replace({
    1: "15-16",
    2: "17-19",
    3: "20-21",
    4: "22-24",
    5: "25-26",
    6: "27-29",
})

raw["SEX"] = raw["SEX"].replace({
    1: "M",
    2: "F",
})

raw["MARSTAT"] = raw["MARSTAT"].replace({
    1: "Married",
    2: "Living in common-law",
    3: "Widowed",
    4: "Separated",
    5: "Divorced",
    6: "Single, never married",
})

raw["EDUC"] = raw["EDUC"].replace({
    0: "0-8 years",
    1: "Some high school",
    2: "High school graduate",
    3: "Some postsecondary",
    4: "Postsecondary certificate or diploma",
    5: "Bachelor's degree",
    6: "Above bachelor's degree",
})

raw["MJH"] = raw["MJH"].replace({
    1: "Single jobholder, including job changers",
    2: "Multiple jobholder",
})

raw["EVERWORK"] = raw["EVERWORK"].replace({
    1: "Yes, within last year",
    2: "Yes, more than 1 year ago",
    3: "No, never worked",
})

raw["FTPTLAST"] = raw["FTPTLAST"].replace({
    1: "Full-time (30 hours or more)",
    2: "Part-time (1 to 29 hours)",
})

raw["COWMAIN"] = raw["COWMAIN"].replace({
    1: "Public sector employees",
    2: "Private sector employees",
    3: "Self-employed incorporated, with paid help",
    4: "Self-employed incorporated, no paid help",
    5: "Self-employed unincorporated, with paid help",
    6: "Self-employed unincorporated, no paid help",
    7: "Unpaid family worker",
})

raw["IMMIG"] = raw["IMMIG"].replace({
    1: "Immigrant, landed 10 or less years earlier",
    2: "Immigrant, landed more than 10 years earlier",
    3: "Non-immigrant",
})

raw["NAICS_21"] = raw["NAICS_21"].replace({
    1: "Agriculture",
    2: "Forestry and logging and support activities for forestry",
    3: "Fishing, hunting and trapping",
    4: "Mining, quarrying, and oil and gas extraction",
    5: "Utilities",
    6: "Construction",
    7: "Manufacturing - durable goods",
    8: "Manufacturing - non-durable goods",
    9: "Wholesale trade",
    10: "Retail trade",
    11: "Transportation and warehousing",
    12: "Finance and insurance",
    13: "Real estate and rental and leasing",
    14: "Professional, scientific and technical services",
    15: "Business, building and other support services",
    16: "Educational services",
    17: "Health care and social assistance",
    18: "Information, culture and recreation",
    19: "Accommodation and food services",
    20: "Other services (except public administration)",
    21: "Public administration",
})

raw["NOC_10"] = raw["NOC_10"].replace({
    1: 'Management occupations',
    2: 'Business, finance and administration occupations',
    3: 'Natural and applied sciences and related occupations',
    4: 'Health occupations',
    5: 'Occupations in education, law and social, community and government services',
    6: 'Occupations in art, culture, recreation and sport',
    7: 'Sales and service occupations',
    8: 'Trades, transport and equipment operators and related occupations',
    9: 'Natural resources, agriculture and related production occupations',
    10: 'Occupations in manufacturing and utilities',
})

raw["NOC_40"] = raw["NOC_40"].replace({
    1: 'Senior management occupations',
    2: 'Specialized middle management occupations',
    3: 'Middle management occupations in retail and wholesale trade and customer services',
    4: 'Middle management occupations in trades, transportation, production and utilities',
    5: 'Professional occupations in business and finance',
    6: 'Administrative and financial supervisors and administrative occupations',
    7: 'Finance, insurance and related business administrative occupations',
    8: 'Office support occupations',
    9: 'Distribution, tracking and scheduling co-ordination occupations',
    10: 'Professional occupations in natural and applied sciences',
    11: 'Technical occupations related to natural and applied sciences',
    12: 'Professional occupations in nursing',
    13: 'Professional occupations in health (except nursing)',
    14: 'Technical occupations in health',
    15: 'Assisting occupations in support of health services',
    16: 'Professional occupations in education services',
    17: 'Professional occupations in law and social, community and government services',
    18: 'Paraprofessional occupations in legal, social, community and education services',
    19: 'Occupations in front-line public protection services',
    20: 'Care providers and educational, legal and public protection support occupations',
    21: 'Professional occupations in art and culture',
    22: 'Technical occupations in art, culture, recreation and sport',
    23: 'Retail sales supervisors and specialized sales occupations',
    24: 'Service supervisors and specialized service occupations',
    25: 'Sales representatives and salespersons - wholesale and retail trade',
    26: 'Service representatives and other customer and personal services occupations',
    27: 'Sales support occupations',
    28: 'Service support and other service occupations, n.e.c.',
    29: 'Industrial, electrical and construction trades',
    30: 'Maintenance and equipment operation trades',
    31: 'Other installers, repairers and servicers and material handlers',
    32: 'Transport and heavy equipment operation and related maintenance occupations',
    33: 'Trades helpers, construction labourers and related occupations',
    34: 'Supervisors and technical occupations in natural resources, agriculture and related production',
    35: 'Workers in natural resources, agriculture and related production',
    36: 'Harvesting, landscaping and natural resources labourers',
    37: 'Processing, manufacturing and utilities supervisors and central control operators',
    38: 'Processing and manufacturing machine operators and related production workers',
    39: 'Assemblers in manufacturing',
    40: 'Labourers in processing, manufacturing and utilities',
})

raw["YABSENT"] = raw["YABSENT"].replace({
    0: 'Other reasons',
    1: 'Own illness or disability',
    2: 'Personal or family responsibilities',
    3: 'Vacation',
})

raw["PAYAWAY"] = raw["PAYAWAY"].replace({
    1: 'Yes',
    2: 'No',
})

raw["FTPTMAIN"] = raw["FTPTMAIN"].replace({
    1: 'Full-time',
    2: 'Part-time',
})

raw["YAWAY"] = raw["YAWAY"].replace({
    0: 'Other reasons',
    1: 'Own illness or disability',
    2: 'Personal or family responsibilities',
    3: 'Vacation or civic holiday',
    4: 'Working short-time',
})

raw["WHYPT"] = raw["WHYPT"].replace({
    0: 'Other reasons',
    1: 'Own illness or disability',
    2: 'Caring for children',
    3: 'Other personal or family responsibilities',
    4: 'Going to school',
    5: 'Personal preference',
    6: 'Business conditions or could not find full-time work, looked for full-time work in last month',
    7: 'Business conditions or could not find full-time work, did not look for full-time work in last month',
})

raw["UNION"] = raw["UNION"].replace({
    1: 'Union member',
    2: 'Not a member but covered by a union contract or collective agreement',
    3: 'Non-unionized',
})

raw["PERMTEMP"] = raw["PERMTEMP"].replace({
    1: 'Permanent',
    2: 'Temporary, seasonal job',
    3: 'Temporary, term or contract job',
    4: 'Temporary, casual or other temorary jobs',
})

raw["ESTSIZE"] = raw["ESTSIZE"].replace({
    1: 'Less than 20 employees',
    2: '20 to 99 employees',
    3: '100 to 500 employees',
    4: 'More than 500 employees',
})

raw["FIRMSIZE"] = raw["FIRMSIZE"].replace({
    1: 'Less than 20 employees',
    2: '20 to 99 employees',
    3: '100 to 500 employees',
    4: 'More than 500 employees',
})

raw["FLOWUNEM"] = raw["FLOWUNEM"].replace({
    1: 'Job losers, temporary layoff',
    2: 'Job losers, permanent layoff',
    3: 'Job leavers',
    4: 'Job leavers/losers (status unknown), worked more than 1 year ago ',
    5: 'New entrants',
    6: 'Re-entrants, worked 1 year ago or less',
    7: 'Re-entrants, worked more than 1 year ago',
    8: 'Future starts',
})

raw["UNEMFTPT"] = raw["UNEMFTPT"].replace({
    1: 'Full-time',
    2: 'Part-time',
    3: 'Future starts',
})

raw["WHYLEFTO"] = raw["WHYLEFTO"].replace({
    0: 'Job leavers, other reasons',
    1: 'Job leavers, own illness or disability',
    2: 'Job leavers, personal or family responsibilities',
    3: 'Job leavers, going to school',
    4: 'Job losers, laid off',
    5: 'Job leavers, retired',
})

raw["WHYLEFTN"] = raw["WHYLEFTN"].replace({
    0: 'Job leavers, other reasons',
    1: 'Job leavers, own illness or disability',
    2: 'Job leavers, caring for children',
    3: 'Job leavers, pregnancy',
    4: 'Job leavers, personal or family responsibilities',
    5: 'Job leavers, going to school',
    6: 'Job leavers, dissatisfied',
    7: 'Job leavers, retired',
    8: 'Job leavers, business sold or closed down (self-employed)',
    9: 'Job losers, end of seasonal job (employee)',
    10: 'Job losers, end of temporary or casual (employee)',
    11: 'Job losers, company moved or out of business (employee)',
    12: 'Job losers, business conditions (employee)',
    13: 'Job losers, dismissal or other reasons',
})

raw["AVAILABL"] = raw["AVAILABL"].replace({
    1: 'Not available',
    2: 'Yes, available',
})

raw["LKPUBAG"] = raw["LKPUBAG"].replace({
    1: 'Yes',
})

raw["LKEMPLOY"] = raw["LKEMPLOY"].replace({
    1: 'Yes',
})

raw["LKRELS"] = raw["LKRELS"].replace({
    1: 'Yes',
})

raw["LKATADS"] = raw["LKATADS"].replace({
    1: 'Yes',
})

raw["LKANSADS"] = raw["LKANSADS"].replace({
    1: 'Yes',
})

raw["LKOTHERN"] = raw["LKOTHERN"].replace({
    1: 'Yes',
})

raw["PRIORACT"] = raw["PRIORACT"].replace({
    0: 'Other',
    1: 'Working',
    2: 'Managing a home',
    3: 'Going to school',
})

raw["YNOLOOK"] = raw["YNOLOOK"].replace({
    0: 'Wanted work, reason - other',
    1: 'Wanted work, reason - own illness or disability',
    2: 'Wanted work, reason - caring for children',
    3: 'Wanted work, reason - other personal or family responsibilities',
    4: 'Wanted work, reason - school',
    5: 'Wanted work, reason - awaiting recall or reply',
    6: 'Wanted work, reason - discouraged',
})

raw["TLOLOOK"] = raw["TLOLOOK"].replace({
    1: 'Yes',
    2: 'No',
})

raw["SCHOOLN"] = raw["SCHOOLN"].replace({
    1: 'Non-student',
    2: 'Full-time student',
    3: 'Part-time student',
})

raw["EFAMTYPE"] = raw["EFAMTYPE"].replace({
    1: 'Person not in an economic family',
    2: 'Dual-earner couple, no children or none under 25',
    3: 'Dual-earner couple, youngest child 0 to 17',
    4: 'Dual-earner couple, youngest child 18 to 24',
    5: 'Single-earner couple, male employed, no children or none under 25',
    6: 'Single-earner couple, male employed, youngest child 0 to 17',
    7: 'Single-earner couple, male employed, youngest child 18 to 24',
    8: 'Single-earner couple, female employed, no children or none under 25',
    9: 'Single-earner couple, female employed, youngest child 0 to 17',
    10: 'Single-earner couple, female employed, youngest child 18 to 24',
    11: 'Non-earner couple, no children or none under 25',
    12: 'Non-earner couple, youngest child 0 to 17',
    13: 'Non-earner couple, youngest child 18 to 24',
    14: 'Lone-parent family, parent employed, youngest child 0 to 17',
    15: 'Lone-parent family, parent employed, youngest child 18 to 24',
    16: 'Lone-parent family, parent not employed, youngest child 0 to 17',
    17: 'Lone-parent family, parent not employed, youngest child 18 to 24',
})

raw["AGYOWNK"] = raw["AGYOWNK"].replace({
    1: 'Youngest child less than 6 years',
    2: 'Youngest child 6 to 12 years',
    3: 'Youngest child 13 to 17 years',
    4: 'Youngest child 18 to 24 years',
})

raw.columns = [
    'Survey year',
    'Survey month',
    'Labour force status',
    'Province',
    'Nine largest CMAs',
    'Five-year age group of respondent',
    'Age in 2 and 3 year groups, 15 to 29',
    'Sex of respondent',
    'Marital status of respondent',
    'Highest educational attainment',
    'Single or multiple jobholder',
    'Not currently employed, worked in the past',
    'Full- or part-time status of last job',
    'Class of worker, main job',
    'Immigrant status',
    'Industry of main job',
    'Occupation at main job',
    'Occupation at main job - Detail',
    'Reason of absence, full week',
    'Number of weeks absent from work',
    'Paid for time off, full-week absence only',
    'Usual hours worked per week at main job',
    'Actual hours worked per week at main job',
    'Full- or part-time status at main or only job',
    'Usual hours worked per week at all jobs',
    'Actual hours worked per week at all jobs',
    'Hours away from work, part-week absence only',
    'Reason for part-week absence',
    'Paid overtime hours in reference week',
    'Unpaid overtime hours in reference week',
    'Number of overtime or extra hours worked',
    'Reason for part-time work',
    'Job tenure with current employer (months)',
    'Job tenure with previous employer (months)',
    'Usual hourly wages, employees only',
    'Union status, employees only',
    'Job permanency, employees only',
    'Establishment size',
    'Firm size',
    'Duration of unemployment (weeks)',
    'Flows into unemployment',
    'Unemployed, type of job wanted',
    'Reason for leaving job during previous year',
    'Reason for leaving job during previous year',
    'Duration of joblessness (months)',
    'Availability during the reference week',
    'Unemployed, used public employment agency',
    'Unemployed, checked with employers directly',
    'Unemployed, checked with friends or relatives',
    'Unemployed, looked at job ads',
    'Unemployed, placed or answered ads',
    'Unemployed, other methods',
    'Main activity before started looking for work',
    'Reason for not looking for work during the reference week',
    'Temporary layoff, looked for work during the last four weeks',
    'Current student status',
    'Type of economic family',
    'Age of youngest child',
    'Standard final weight',
  ]

raw.loc[:, ["Usual hours worked per week at main job",
                              "Actual hours worked per week at main job",
                              "Usual hours worked per week at all jobs",
                              "Actual hours worked per week at all jobs"]
] = (raw.loc[:, ["Usual hours worked per week at main job",
                              "Actual hours worked per week at main job",
                              "Usual hours worked per week at all jobs",
                              "Actual hours worked per week at all jobs"]
] / 10)

date = raw["Survey year"].astype('str') + " - " + raw["Survey month"].astype('str')
date = pd.to_datetime(date)

raw.insert(0, 'Survey date', date)
raw = raw.drop(columns=["Survey year", "Survey month"])

display(raw)

        Survey date  ...  Standard final weight
REC_NUM              ...
1        2021-10-01  ...                    125
2        2021-10-01  ...                    186
3        2021-10-01  ...                    181
4        2021-10-01  ...                    144
5        2021-10-01  ...                    175
...             ...  ...                    ...
86858    2021-08-01  ...                     98
86859    2021-08-01  ...                    231
86860    2021-08-01  ...                     76
86861    2021-08-01  ...                    148
86862    2021-08-01  ...                    398

[259466 rows x 58 columns]

## Occupations list

In [ ]:
occupations_list = raw["Occupation at main job - Detail"].unique()

display(occupations_list)

array(['Processing, manufacturing and utilities supervisors and central control operators',
       'Professional occupations in nursing', 'Sales support occupations',
       'Professional occupations in business and finance', nan,
       'Technical occupations in art, culture, recreation and sport',
       'Sales representatives and salespersons - wholesale and retail trade',
       'Administrative and financial supervisors and administrative occupations',
       'Middle management occupations in retail and wholesale trade and customer services',
       'Maintenance and equipment operation trades',
       'Industrial, electrical and construction trades',
       'Service representatives and other customer and personal services occupations',
       'Service supervisors and specialized service occupations',
       'Specialized middle management occupations',
       'Professional occupations in law and social, community and government services',
       'Service support and other service occupations, n.e.c.',
       'Professional occupations in education services',
       'Professional occupations in natural and applied sciences',
       'Retail sales supervisors and specialized sales occupations',
       'Other installers, repairers and servicers and material handlers',
       'Workers in natural resources, agriculture and related production',
       'Middle management occupations in trades, transportation, production and utilities',
       'Transport and heavy equipment operation and related maintenance occupations',
       'Assisting occupations in support of health services',
       'Finance, insurance and related business administrative occupations',
       'Senior management occupations', 'Office support occupations',
       'Care providers and educational, legal and public protection support occupations',
       'Trades helpers, construction labourers and related occupations',
       'Paraprofessional occupations in legal, social, community and education services',
       'Professional occupations in health (except nursing)',
       'Technical occupations related to natural and applied sciences',
       'Supervisors and technical occupations in natural resources, agriculture and related production',
       'Distribution, tracking and scheduling co-ordination occupations',
       'Assemblers in manufacturing', 'Technical occupations in health',
       'Processing and manufacturing machine operators and related production workers',
       'Labourers in processing, manufacturing and utilities',
       'Professional occupations in art and culture',
       'Harvesting, landscaping and natural resources labourers',
       'Occupations in front-line public protection services'],
      dtype=object)

# Overtime

In [ ]:
overtime = raw.copy()
overtime["Number of overtime or extra hours worked"] = overtime["Number of overtime or extra hours worked"].fillna(0)

        Survey date  ...  Standard final weight
REC_NUM              ...
1        2021-10-01  ...                    125
2        2021-10-01  ...                    186
3        2021-10-01  ...                    181
4        2021-10-01  ...                    144
5        2021-10-01  ...                    175
...             ...  ...                    ...
86858    2021-08-01  ...                     98
86859    2021-08-01  ...                    231
86860    2021-08-01  ...                     76
86861    2021-08-01  ...                    148
86862    2021-08-01  ...                    398

[259466 rows x 58 columns]

## Average overtime for nurses

In [ ]:
overtime_nurses = overtime[overtime["Occupation at main job - Detail"] == "Professional occupations in nursing"]
overtime_nurses = overtime_nurses.groupby(["Province", "Survey date"]).mean().reset_index()

overtime_nurses_pivot = pd.pivot(overtime_nurses, index=["Province"], columns="Survey date", values="Number of overtime or extra hours worked")

display(overtime_nurses_pivot)

Survey date                2021-08-01  2021-09-01  2021-10-01
Province
Alberta                     18.022989   22.511111   25.275510
British Columbia            16.280992   24.325581   21.532847
Manitoba                    17.647059   28.656716   18.776224
New Brunswick               19.333333   16.785714   29.866667
Newfoundland and Labrador   13.673469   18.541667   11.790698
Nova Scotia                 18.235294   23.984375   26.825397
Ontario                     13.620072   11.398551   20.275748
Prince Edward Island         8.424242    4.500000   13.041667
Quebec                      20.334951   20.742268   22.545455
Saskatchewan                29.578947   20.061728   22.686747

## Overtime for various professions

In [ ]:
# overtime_october = overtime_october.groupby(["Occupation at main job - Detail"]).mean().reset_index()
overtime_all = overtime.groupby(["Occupation at main job - Detail", "Survey date"]).mean().reset_index()

overtime_all_pivot = pd.pivot(overtime_all, index=["Occupation at main job - Detail"], columns="Survey date", values="Number of overtime or extra hours worked")

overtime_all_pivot = overtime_all_pivot.sort_values("2021-10-01", ascending=False)

display(overtime_all_pivot)

Survey date                                         2021-08-01  ...  2021-10-01
Occupation at main job - Detail                                 ...
Occupations in front-line public protection ser...   30.141243  ...   36.919753
Specialized middle management occupations            21.821622  ...   31.311327
Professional occupations in education services        6.164010  ...   31.170520
Senior management occupations                        29.462810  ...   29.642857
Processing, manufacturing and utilities supervi...   21.004886  ...   27.609215
Supervisors and technical occupations in natura...   20.222527  ...   23.345428
Professional occupations in nursing                  17.533628  ...   21.719237
Maintenance and equipment operation trades           18.965288  ...   21.680020
Transport and heavy equipment operation and rel...   17.243277  ...   17.062181
Processing and manufacturing machine operators ...   14.349345  ...   16.984649
Industrial, electrical and construction trades       15.239259  ...   15.762164
Trades helpers, construction labourers and rela...   15.335125  ...   15.667293
Technical occupations related to natural and ap...   15.559723  ...   13.423429
Other installers, repairers and servicers and m...   15.166265  ...   13.263274
Labourers in processing, manufacturing and util...    7.854503  ...   12.783251
Assemblers in manufacturing                           7.862669  ...   12.079767
Technical occupations in health                      10.453279  ...   11.928694
Professional occupations in law and social, com...    9.369594  ...   11.924626
Professional occupations in business and finance      8.410619  ...   11.375550
Professional occupations in natural and applied...   12.771681  ...   11.362851
Harvesting, landscaping and natural resources l...    8.521008  ...   10.380531
Assisting occupations in support of health serv...    8.605475  ...    9.850039
Distribution, tracking and scheduling co-ordina...    9.032086  ...    9.481707
Workers in natural resources, agriculture and r...   12.743222  ...    9.268868
Professional occupations in health (except nurs...    6.566667  ...    8.744565
Middle management occupations in trades, transp...    8.336207  ...    8.049908
Administrative and financial supervisors and ad...    7.130277  ...    7.809830
Retail sales supervisors and specialized sales ...    6.919589  ...    7.442308
Middle management occupations in retail and who...    7.039725  ...    6.832727
Care providers and educational, legal and publi...    4.023058  ...    6.121281
Paraprofessional occupations in legal, social, ...    5.586552  ...    6.059328
Service supervisors and specialized service occ...    7.749304  ...    5.950783
Professional occupations in art and culture           5.824524  ...    5.922222
Service representatives and other customer and ...    5.075425  ...    5.201800
Service support and other service occupations, ...    3.974034  ...    5.071844
Sales representatives and salespersons - wholes...    4.506024  ...    4.859584
Finance, insurance and related business adminis...    4.966706  ...    4.837485
Technical occupations in art, culture, recreati...    6.689873  ...    4.493278
Office support occupations                            4.489641  ...    4.239034
Sales support occupations                             2.018905  ...    3.007147

[40 rows x 3 columns]