# COVID-19 hospitalizations
*March 18, 2022*

Let's take a very quick look at COVID-19 hospitalizations in Canada using PHAC hospitalization data for a simple hospitalization line chart.

Import Panda and read in the data.

In [3]:
import pandas as pd

raw = pd.read_csv("../raw/RAW 2022 PHAC COVID.csv")

raw.head()

,Date,BEDCAP_ICU,VENTCAP_ICU,BEDCAP_OTHER,VENTCAP_OTHER,COVID_NEWICU,COVID_ICU,COVID_NEWOTHER,COVID_OTHER,COVID_VENT,VENTCAP_TOTAL,NONCOVID_ICU,NONCOVID_OTHER,NONCOVID_VENT,COVID_HOSP
0,2020-04-01,2817,2058,30172,536,0,193,0,327,127,2594,169,6540,106,520
1,2020-04-02,3681,2089,40123,557,0,293,0,427,204,2646,389,12463,0,720
2,2020-04-03,3681,2089,40016,557,0,292,0,450,215,2646,384,12369,0,742
3,2020-04-04,3681,2089,40381,557,0,301,0,498,222,2646,1,6541,0,799
4,2020-04-05,3681,2089,40721,557,0,324,0,510,227,2646,0,6514,0,834

Now it's as simple as isolating the right column, in this case just total hospitalizations.

In [9]:
hospitalizations = raw.loc[:, ["Date", "COVID_HOSP"]].set_index("Date")

hospitalizations.head()

            COVID_HOSP
Date
2020-04-01         520
2020-04-02         720
2020-04-03         742
2020-04-04         799
2020-04-05         834
...                ...
2022-03-10        4369
2022-03-11        4258
2022-03-12        4153
2022-03-13        4154
2022-03-14        4177

[713 rows x 1 columns]

And that's all there is to it. I copied this data over to Datawrapper to finish up [the visualization](https://www.datawrapper.de/_/hZqR1/).

\-30\-